### ISSUE TITLE
Doc improvements

### ISSUE THREAD

**Issue by devinpearson** [FrikkieSnyman/investec-api#4]
Hey, Frikkie love the connector, I was looking through the Readme and thought I would share some suggestions. 

Add an NPM badge, as you aren't keeping the GitHub releases on par with the nom releases, it would be easier to see the npm release version on the readme. 

Add an example of how to instantiate the Client with the api key. I see the code is there the example in the Readme doesn't explain it.

The payments example has a typo you have a - instead of a =
`const payment - await account.pay`

Look at putting a link to the original Investec api docs to help fill out the context of the connector.

**Comment by FrikkieSnyman** [comment]
Hey @devinpearson 

Great suggestions, thanks!

I'll try and get round to it

**Comment by FrikkieSnyman** [comment]
Done! I'll look into why the releases are not being tagged on github though. Pretty sure I had that going 🙈
