### ISSUE TITLE
Add support for the sandbox Investec API endpoint

### ISSUE THREAD

**Issue by shailen-naidoo** [FrikkieSnyman/investec-api#6]
Hi @FrikkieSnyman thanks for putting this amazing library together, it has been such a pleasure using the library. The only thing that I have bumped into that would add so much value to the library is if it supports the sandbox endpoint https://openapisandbox.investec.com.

I can do a PR for this and if you are happy with it, it can be merged into the main library. There are a few ways we could go about the implementation for it:

1. Added a flag option to the `Client.create(clientId, secret, apiKey, token, sandbox: boolean)`
2. We can expose the endpoint to allow the user to provide the endpoint but since we know that there are only 2 endpoints it makes more sense for us to manage that internally in the library.

I can put together a PR and then you can have a look at it if you are happy with the changes 😄

**Comment by FrikkieSnyman** [comment]
Fixed in #8
